exchangeStrategies:
- on: binance
  getIndNotStandard:
    symbol: BTCUSDT
    interval: 5m
    window: 20
   
backtest:
  startTime: "2022-01-01"
  endTime: "2022-03-01"
  symbols:
  - BTCUSDT
  sessions: [binance]
  # syncSecKLines: true
  accounts:
    binance:
      makerFeeRate: 0.0%
      takerFeeRate: 0.075%
      balances:
        BTC: 0.0
        USDT: 10_000.0