// Code generated by "callbackgen -type PriceCrossMa"; DO NOT EDIT.

package indicator

import ()

func (inc *PriceCrossMa) OnUpdate(cb func(value float64)) {
	inc.updateCallbacks = append(inc.updateCallbacks, cb)
}

func (inc *PriceCrossMa) EmitUpdate(value float64) {
	for _, cb := range inc.updateCallbacks {
		cb(value)
	}
}
